apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: qrpayment-hpa 
  namespace: jc-pre-prod-microservices
spec:
  scaleTargetRef:
    apiVersion: apps.openshift.io/v1 
    kind: DeploymentConfig 
    name: qrpayment-microservice
  minReplicas: 1 
  maxReplicas: 1 
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 90
