const HTTP_STATUS = {
    CONTINUE: 100,
    SWITCHING_PROTOCOLS: 101,
    PROCESSING: 102,
    OK: 200,
    CREATED: 201,
    ACCEPTED: 202,
    NON_AUTHORITATIVE_INFORMATION: 203,
    NO_CONTENT: 204,
    RESET_CONTENT: 205,
    PARTIAL_CONTENT: 206,
    MULTI_STATUS: 207,
    MULTIPLE_CHOICES: 300,
    MOVED_PERMANENTLY: 301,
    MOVED_TEMPORARILY: 302,
    SEE_OTHER: 303,
    NOT_MODIFIED: 304,
    USE_PROXY: 305,
    TEMPORARY_REDIRECT: 307,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    PAYMENT_REQUIRED: 402,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    METHOD_NOT_ALLOWED: 405,
    NOT_ACCEPTABLE: 406,
    PROXY_AUTHENTICATION_REQUIRED: 407,
    REQUEST_TIME_OUT: 408,
    CONFLICT: 409,
    GONE: 410,
    LENGTH_REQUIRED: 411,
    PRECONDITION_FAILED: 412,
    REQUEST_ENTITY_TOO_LARGE: 413,
    'REQUEST-URI TOO LARGE': 414,
    'UNSUPPORTED MEDIA TYPE': 415,
    'REQUESTED RANGE NOT SATISFIABLE': 416,
    'EXPECTATION FAILED': 417,
    "I'M A TEAPOT": 418,
    UNPROCESSABLE_ENTITY: 422,
    LOCKED: 423,
    'FAILED DEPENDENCY': 424,
    'UNORDERED COLLECTION': 425,
    'UPGRADE REQUIRED': 426,
    'PRECONDITION REQUIRED': 428,
    'TOO MANY REQUESTS': 429,
    'REQUEST HEADER FIELDS TOO LARGE': 431,
    INTERNAL_SERVER_ERROR: 500,
    NOT_IMPLEMENTED: 501,
    BAD_GATEWAY: 502,
    SERVICE_UNAVAILABLE: 503,
    GATEWAY_TIME_OUT: 504,
    'HTTP VERSION NOT SUPPORTED': 505,
    'VARIANT ALSO NEGOTIATES': 506,
    INSUFFICIENT_STORAGE: 507,
    BANDWIDTH_LIMIT_EXCEEDED: 509,
    NOT_EXTENDED: 510,
    NETWORK_AUTHENTICATION_REQUIRED: 511,
};


const NON_JC_PAYMENT_STATUS = {
    PENDING: 1,
    IN_PROGRESS: 2,
    EXPIRED: 3,
    COMPLETED: 4,
    REFUNDED: 5,
    REFUND_FAILED: 6,
    INSTANT_REFUND: 7,
    CPS_FAILURE: 8,
    REDEEM_FAILURE: 9,
    INSTANT_REFUND_FAILURE: 10
};

const NON_JC_PAYMENT_TYPE = {
    CNIC: "cnic",
    MSISDN: "msisdn",
    REFUND: "refund"
};

const C2G_USER_STATUS = {
    USER_IS_NOT_JC: 0,
    USER_IS_JC: 1,
    USER_CATEGORY_STATUS_NOT_BLOCKED: 2,
    USER_CATEGORY_STATUS_BLOCKED: 3,
    USER_INIT_SUCCESS: 4,
    USER_INIT_FAIL: 5,
    USER_CONFIRM_SUCCESS: 6,
    USER_CONFIRM_FAIL: 7,
};

const CASH_TO_GOOD_BALANCE_STATUS = {
    UNLOCK: 0,
    LOCK: 1,
};

const MAYA_PAYMENT_STATUS = {
    INIT_PASSED: "INIT_PASSED",
    INIT_FAILED: "INIT_FAILED",
    CONFIRM_PASSED: "CONFIRM_PASSED",
    CONFIRM_FAILED: "CONFIRM_FAILED",
    MAYA_PAYMENT_INFO_PASSED: "MAYA_PAYMENT_INFO_PASSED",
    MAYA_PAYMENT_INFO_FAILED: "MAYA_PAYMENT_INFO_FAILED",
    REFUND_PASSED: "REFUND_PASSED",
    REFUND_FAILED: "REFUND_FAILED"
};

const REPORTING_TABLES = {
    NONJAZZCASH: "NONJAZZCASH",
    FAVORITE_LIST: "FAVORITE_LIST",
    SPSU_DISBURSEMENTS: "SPSU_DISBURSEMENTS",
    UBPSCAN: "UBPSCAN"
}

const REPORTING_CASE = {
    INSERT: "insert",
    REDEEM: "redeem",
    REDEEM_FAILURE: "redeem_failure",
    REFUND: "refund",
    REFUND_FAILURE: "refund_failure",
    TRANACTION_FAILED_MONGO: "transaction_failed_mongo",
    UPDATE: "update",
    FETCH_BY_ID: "fetch_by_id",
    FETCH_BY_TRXID: "fetch_by_trid"
}


const RAAST_API = {
    IBFT: process.env.RAAST_API_IBFT_URL || config.externalServices.raastApi.ibft,
    TITLE_FETCH: process.env.RAAST_API_TITLE_FETCH_URL || config.externalServices.raastApi.titleFetch,
    DEFAULT_ACC_ALIAS: process.env.RAAST_API_DEFAULT_ACC_ALIAS || config.externalServices.raastApi.defaultAccAlias,
    CREATE_IBAN: process.env.RAAST_CREATE_IBAN || config.externalServices.raastApi.createIban,
    GET_ACC_LIMIT: process.env.ACCOUNT_MANAGEMENT_API_ACC_LIMITS || config.externalServices.accountManagementAPI.accountLimits,
    DEFAULT_ACC_BY_ALIAS: process.env.RAAST_API_DEFAULT_ACC_BY_ALIAS || config.externalServices.raastApi.defaultAccountByAlias
}

const RAAST_PAYMENT_TYPE = {
    alias: "alias",
    iban: "iban"
}

module.exports = {
    HTTP_STATUS,
    NON_JC_PAYMENT_STATUS,
    NON_JC_PAYMENT_TYPE,
    C2G_USER_STATUS,
    CASH_TO_GOOD_BALANCE_STATUS,
    MAYA_PAYMENT_STATUS,
    REPORTING_TABLES,
    REPORTING_CASE,
    RAAST_API,
    RAAST_PAYMENT_TYPE
}