kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: qrpayment-microservice
  namespace: m11s
  labels:
    app: qrpayment-microservice
    app.kubernetes.io/part-of: m11s
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - qrpayment-microservice
        from:
          kind: ImageStreamTag
          namespace: m11s
          name: 'qrpayment-microservice:latest'
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    app: qrpayment-microservice
    deploymentconfig: qrpayment-microservice
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: qrpayment-microservice
        deploymentconfig: qrpayment-microservice
      annotations:
        openshift.io/generated-by: jenkins-pipeline
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: qrpayment-microservice
          image: image-registry.openshift-image-registry.svc:5000/m11s/qrpayment-microservice:latest
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MONGO_CONNECTION
            valueFrom:
              secretKeyRef:
                key: mongo-connection-string
                name: mongo-connection-payment-and-transaction
          - name: ESB_URL
            value: http://cps-rest-service-r1-is.ace:7800/rest/requestmgrservice/v1/sync
          - name: MASTER_DATA_API_GET_RESPCODE_URL
            value: http://masterdata-microservice:3000/rest/api/v1/masterdata/responseCodes
          - name: GET_MERCHANT_LOGO
            value: http://masterdata-microservice:3000/rest/api/v2/masterfile/files/get?fileURL=
          - name: ENCRYPTION_ENABLED
            value: 'true'
          - name: ACCOUNT_MANAGEMENT_API_ADD_TO_FAV_URL
            value: http://account-management-microservice:3000/addToFavouritList
          - name: AKSA_URL
            value: https://qrpaybe.jazzcash.com.pk:7070
          - name: AKSA_MERCHANT_PATH
            value: /api/Account/CheckQRCode
          - name: SMS_NOTIFICATION_URL
            value: http://notification-microservice:3000/rest/api/v1/notification/sms
          - name: EMAIL_NOTIFICATION_URL
            value: http://notification-microservice:3000/rest/api/v1/notification/email
          - name: PUSH_NOTIFICATION_URL
            value: http://notification-microservice:3000/rest/api/v1/notification/pushnotification
          - name: PUSH_NOTIFICATION_MSISDN_URL
            value: http://notification-microservice:3000/rest/api/v1/notification/pushnotification/msisdn
          - name: USER_PROFILE_URL
            value: http://account-management-microservice:3000/rest/api/v1/account/profile
          - name: USER_PROFILE_ONPREM_URL
            value: http://account-management-microservice:3000/rest/api/v1/account/profile
          - name: QR_CODE_URL
            value: http://account-management-microservice:3000/rest/api/v1/account/qrcode/display
          - name: MERCHANT_RATING_CONFIG_MASTER_DATA
            value: http://masterdata-microservice:3000/rest/api/v1/masterdata/configuration?key=QR_RATINGS
          - name: MERCHANT_RATING_CONFIG_ACC_MNG
            value: http://account-management-microservice:3000/rest/api/v1/account/profile/minratingamount?internal=true&msisdn=
          - name: QR_RATING_API
            value: http://account-management-microservice:3000/rest/api/v1/account/profile/rating
          - name: SMS_NOTIFIERS
            value: http://account-management-microservice:3000/rest/api/v1/merchant/notifiers/sms
          - name: CREATE_OTHER_PROFILE
            value: http://account-management-microservice:3000/rest/api/v1/account/otherprofile
          - name: CASH_REPAYMENT_USECASE
            value: ReadyCashRePayment
          - name: FONEPAY_ENABLED
            value: 'false'
          - name: KAFKA_DRAIN_CHECK
            value: 'false'
          - name: REQUEST_TO_PAY_SCHEDULAR_CRON
            value: '0 12 * * *'
          - name: SPECIALMSISDNTOCHECKINTRXHISTORY
            value: 923079770177,923079770309,923008523283
          - name: GET_KPKPSC_CONSUMER_URL
            value: "http://kpkpscservice-http-ace.apps.tjcocp.jazz.com.pk:80/kpkpscservice/v1/GenerateConsumerNumber"
          - name: CONSUMER_GROUP_ID
            valueFrom:
              configMapKeyRef:
                name: consumer-groups
                key: CONSUMER_GROUP_PAYMENT
          - name: CONSUMER_GROUP_USSD_ID
            valueFrom:
              configMapKeyRef:
                name: consumer-groups
                key: CONSUMER_GROUP_USSD      
          - name: THIRD_PARTY_MAP
            valueFrom:
              secretKeyRef:
                key: THIRD_PARTY_MAP
                name: r1-configuration-map
          - name: THIRD_PARTY_MAP_R_FIVE
            valueFrom:
              secretKeyRef:
                name: r5-configuration-map
                key: THIRD_PARTY_MAP_R_FIVE
          - name: IBFT_CONFIGURATION_MAP
            valueFrom:
              secretKeyRef:
                key: IBFT_CONFIGURATION_MAP
                name: ibft-configuration-map
          - name: PRODUCTION_LOG_LEVEL
            value: info
          - name: EP_IBFT_RECEIVER_KEEP_DYNAMIC
            value: 'true'   
          - name: NODE_ENV
            value: live
          - name: ORG_CVID_REQUESTID
            value: 'true'
          - name: MPIN_ENCRYPTION_KEY
            value: 98ae67823eodfj4904jdf34fj045k742
          - name: MPIN_3DES_ENCRYPTION_KEY
            value: 7493jfl;d832kd73$5%&@3!2
          - name: Token_Validation
            value: 'false'
          - name: FONEPAY_USERNAME
            value: 'disable'
          - name: TRANSACTION_HISTORY_TTL
            value: '1800'
          expose: true
          livenessProbe:
            failureThreshold: 12
            httpGet:
              path: /live
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 2
            monitoring:
              labels:
                k8s-app: jazzcash-project
          readinessProbe:
            failureThreshold: 12
            httpGet:
              path: /ready
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 1
                                
          resources:
            limits:
              cpu: 200m
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler

